#ifndef KEYCODE_H_INCLUDED
#define KEYCODE_H_INCLUDED 1

#define KEYCODE_ESCAPE 57
#define KEYCODE_LEFT_CONTROL 58
#define KEYCODE_LEFT_SHIFT 59
#define KEYCODE_RIGHT_SHIFT 60
#define KEYCODE_LEFT_ALT 61
#define KEYCODE_CAPS_LOCK 62
#define KEYCODE_NUM_LOCK 63
#define KEYCODE_SCROLL_LOCK 64

#define KEYCODE_FUNCTION_PLUS_N 64

#define KEYCODE_KEYPAD_SLASH 77
#define KEYCODE_KEYPAD_ENTER 78

#define KEYCODE_RIGHT_CONTROL 80
#define KEYCODE_ALTGR 81
#define KEYCODE_HOME 82
#define KEYCODE_CURSOR_UP 83
#define KEYCODE_PAGE_UP 84
#define KEYCODE_CURSOR_LEFT 85
#define KEYCODE_CURSOR_RIGHT 86
#define KEYCODE_END 87
#define KEYCODE_CURSOR_DOWN 88
#define KEYCODE_PAGE_DOWN 89
#define KEYCODE_INSERT 90
#define KEYCODE_LEFT_GUI 91
#define KEYCODE_RIGHT_GUI 92
#define KEYCODE_APPS 93

#define KEYCODE_ACPI_POWER 94
#define KEYCODE_ACPI_SLEEP 95
#define KEYCODE_ACPI_WAKE 96

#endif